server:
  port: 7102

spring:
  application:
    name: cloud-gateway
  data:
    mongodb:
      uri: mongodb://test:123456@10.117.130.110:27017/cloud-note
  cloud:
      gateway:
        routes:
        - id: note
          uri: lb://cloud-note
          predicates:
          - Path=/cloud-note/**
          filters:
          - StripPrefix=1
        - id: work
          uri: http://127.0.0.1:7104/
          predicates:
          - Path=/work/**

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 30000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/